
// Bu dosya, Amadeus'un önceden kaydedilmiş sesli yanıtlarını ve sistem seslerini yönetir.

export const soundEffects: Record<string, string> = {
  'ask_me_whatever': 'sounds/ask_me_whatever.mp3',
  'could_i_help': 'sounds/could_i_help.mp3',
  'dont_add_tina': 'sounds/dont_add_tina.mp3',
  'hello': 'sounds/hello.mp3',
  'humans_software': 'sounds/humans_software.mp3',
  'i_guess': 'sounds/i_guess.mp3',
  'look_forward_to_working': 'sounds/look_forward_to_working.mp3',
  'memories_christina': 'sounds/memories_christina.mp3',
  'memory_complex': 'sounds/memory_complex.mp3',
  'modifying_memories_impossible': 'sounds/modifying_memories_impossible.mp3',
  'nice': 'sounds/nice.mp3',
  'nice_to_meet_okabe': 'sounds/nice_to_meet_okabe.mp3',
  'ok': 'sounds/ok.mp3',
  'perverts_go_to_hell': 'sounds/perverts_go_to_hell.mp3',
  'pervert_confirmed': 'sounds/pervert_confirmed.mp3',
  'pervert_idot_wanttodie': 'sounds/pervert_idot_wanttodie.mp3',
  'pleased_to_meet_you': 'sounds/pleased_to_meet_you.mp3',
  'secret_diary': 'sounds/secret_diary.mp3',
  'senpai_please_dont_tell': 'sounds/senpai_please_dont_tell.mp3',
  'senpai_question': 'sounds/senpai_question.mp3',
  'senpai_questionmark': 'sounds/senpai_questionmark.mp3',
  'senpai_what_we_talkin': 'sounds/senpai_what_we_talkin.mp3',
  'senpai_who_is_this': 'sounds/senpai_who_is_this.mp3',
  'should_christina': 'sounds/should_christina.mp3',
  'sorry': 'sounds/sorry.mp3',
  'sounds_tough': 'sounds/sounds_tough.mp3',
  'still_not_happy': 'sounds/still_not_happy.mp3',
  'this_guy_hopeless': 'sounds/this_guy_hopeless.mp3',
  'tm_nonsense': 'sounds/tm_nonsense.mp3',
  'tm_not_possible': 'sounds/tm_not_possible.mp3',
  'tm_scientist_no_evidence': 'sounds/tm_scientist_no_evidence.mp3',
  'tm_too_early': 'sounds/tm_too_early.mp3',
  'tm_we_dont_know': 'sounds/tm_we_dont_know.mp3',
  'tm_you_said': 'sounds/tm_you_said.mp3',
  'tone': 'sounds/tone.mp3',
  'uh_senpai': 'sounds/uh_senpai.mp3',
  'whats_so_funny_senpai': 'sounds/whats_so_funny_senpai.mp3',
  'what_do_you_want': 'sounds/what_do_you_want.mp3',
  'what_is_it': 'sounds/what_is_it.mp3',
  'who_the_hell_christina': 'sounds/who_the_hell_christina.mp3',
  'why_christina': 'sounds/why_christina.mp3',
  'you_sure': 'sounds/you_sure.mp3',
  'glitch': 'sounds/glitch.mp3',
  // Sistem Atmosfer Sesleri
  'typing': 'sounds/typing_terminal.mp3',
  'incoming': 'sounds/incoming_signal.mp3',
  'warning': 'sounds/warning_signal.mp3',
  'static': 'sounds/static_noise.mp3', // Yeni eklenen parazit sesi
};
