// This file is auto-generated by 'npm run generate-lore'. Do not edit manually.
// It contains the mapping of lore audio files to their Japanese transcripts.

import type { LoreAudio } from '../types';

export const loreAudioData: LoreAudio[] = [];
